# Generated by Django 4.2 on 2025-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_alter_idea_latitude_alter_idea_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
